wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    code_path: code/cleanrl/sac/sac_atari.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1707773016.594097
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.9.5
      5: 0.13.11
      8:
      - 4
      - 5
alpha:
  desc: null
  value: 0.2
autotune:
  desc: null
  value: true
batch_size:
  desc: null
  value: 64
buffer_size:
  desc: null
  value: 1000000
capture_video:
  desc: null
  value: false
cuda:
  desc: null
  value: true
env_id:
  desc: null
  value: BreakoutNoFrameskip-v4
exp_name:
  desc: null
  value: sac_atari
gamma:
  desc: null
  value: 0.99
learning_starts:
  desc: null
  value: 20000.0
policy_lr:
  desc: null
  value: 0.0003
q_lr:
  desc: null
  value: 0.0003
seed:
  desc: null
  value: 1
target_entropy_scale:
  desc: null
  value: 0.89
target_network_frequency:
  desc: null
  value: 8000
tau:
  desc: null
  value: 1.0
torch_deterministic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 5000000
track:
  desc: null
  value: true
update_frequency:
  desc: null
  value: 4
wandb_entity:
  desc: null
  value: null
wandb_project_name:
  desc: null
  value: cleanRL
