# Register Algorithms here.
from .td3 import TD3
from .sac import SAC
from .gumbel_sac import GumbelSAC
from .gumbel_td3 import GumbelTD3
from .qreps_continuous import QREPSContinuous
from .qreps_discrete import QREPSDiscrete
from .gumbel_sac_v2 import GumbelSACV2
from .gumbel_td3_v2 import GumbelTD3V2