alg: QREPSDiscrete
alg_kwargs:
  actor_freq: 2
  alpha: null
  beta: 4.0
  critic_freq: 1
  eta: 0.5
  exp_clip: 8.0
  init_steps: 1
  noise_clip: 0.5
  policy_noise: 0.1
  target_freq: 2
  target_noise: 0.2
  tau: 0.005
  use_target_actor: true
batch_size: null
checkpoint: null
collate_fn: null
dataset: ReplayBuffer
dataset_kwargs:
  batch_size: 256
  capacity: 1000000
  discount: 0.99
  fetch_every: 100
  nstep: 1
env: ALE/Alien-v5
env_kwargs: {}
network: ActorCriticPolicy
network_kwargs:
  actor_class: DiscreteMLPActorV2
  actor_kwargs:
    hidden_layers:
    - 1024
    - 1024
  critic_class: DiscreteMLPCritic
  critic_kwargs:
    hidden_layers:
    - 256
    - 256
  encoder_class: DrQv2Encoder
optim: Adam
optim_kwargs:
  lr: 0.0001
processor: null
processor_kwargs: {}
schedule: null
schedule_kwargs: {}
scheduler: null
seed: null
train_kwargs:
  eval_ep: 10
  eval_freq: 100
  log_freq: 50
  loss_metric: reward
  profile_freq: 250
  total_steps: 200000
  workers: 0
validation_dataset_kwargs: null
