wandb_version: 1

env_id:
  desc: null
  value: CartPole-v1
track:
  desc: null
  value: true
eta:
  desc: null
  value: 0.01
beta:
  desc: null
  value: 0.08
saddle_point_steps:
  desc: null
  value: 300
policy_opt_steps:
  desc: null
  value: 300
discount:
  desc: null
  value: 0.99
wandb_project_name:
  desc: null
  value: qreps
wandb_entity:
  desc: null
  value: null
seed:
  desc: null
  value: 14
exp_name:
  desc: null
  value: cartpole
num_envs:
  desc: null
  value: 1
capture_video:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    code_path: code/qreps_val/experiments/cartpole.py
    python_version: 3.11.6
    cli_version: 0.16.2
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707828927.498364
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 11
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.11.6
      5: 0.16.2
      8:
      - 4
      - 5
      13: darwin-arm64
