alg: GumbelSACV2
alg_kwargs:
  alpha: null
  beta: 3.0
  exp_clip: 10
  init_steps: 500
  init_temperature: 0.1
  loss: gumbel_log_v3
  target_freq: 2
  tau: 0.005
  use_value_log_prob: false
  value_action_noise: 0.0
batch_size: null
checkpoint: null
collate_fn: null
dataset: ReplayBuffer
dataset_kwargs:
  batch_size: 1024
  capacity: 1000000
  discount: 0.99
  fetch_every: 1000
  nstep: 1
env: CheetahRun-v0
env_kwargs: {}
network: ActorCriticPolicy
network_kwargs:
  actor_class: DiagonalGaussianMLPActor
  actor_kwargs:
    hidden_layers:
    - 1024
    - 1024
    log_std_bounds:
    - -5
    - 2
  critic_class: ContinuousMLPCritic
  critic_kwargs:
    hidden_layers:
    - 1024
    - 1024
    num_q_fns: 2
  ortho_init: true
optim: Adam
optim_kwargs:
  lr: 0.0001
processor: null
processor_kwargs: {}
schedule: null
schedule_kwargs: {}
scheduler: null
seed: null
train_kwargs:
  eval_ep: 10
  eval_freq: 1000
  log_freq: 25
  loss_metric: reward
  profile_freq: 250
  total_steps: 200000
  workers: 0
validation_dataset_kwargs: null
